{
 "title": "WaterBox 90.3",
 "time": { "from": "now-30d", "to": "now" },
 "panels": [
  {
   "title": "PH",
   "type": "timeseries",
   "gridPos": { "h": 15, "w": 6, "x": 0, "y": 0 },
   "targets": [
    {
     "rawSql": "SELECT pr.value as ph, pr.time, a.low_limit as low_limit, a.high_limit as high_limit FROM tank_data_schema.parameter_reading as pr\r\nFULL OUTER JOIN tank_data_schema.parameter as p ON p.id = pr.parameter_id\r\nFULL OUTER JOIN tank_data_schema.alarm as a on a.parameter_id = pr.parameter_id\r\nWHERE p.name = 'ph' AND pr.show_in_dashboard = TRUE\r\nORDER BY pr.time;"
    }
   ]
  },
  {
   "title": "Alkalinity",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 6, "x": 6, "y": 0 },
   "targets": [
    {
     "rawSql": "SELECT pr.value as alkalinity, pr.time, a.low_limit as low_limit, a.high_limit as high_limit FROM tank_data_schema.parameter_reading as pr\r\nFULL OUTER JOIN tank_data_schema.parameter as p ON p.id = pr.parameter_id\r\nFULL OUTER JOIN tank_data_schema.alarm as a on a.parameter_id = pr.parameter_id\r\nWHERE p.name = 'alkalinity' AND pr.show_in_dashboard = TRUE\r\nORDER BY pr.time;"
    }
   ]
  },
  {
   "title": "Alkalinity Dosing",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 6, "x": 12, "y": 0 },
   "targets": [
    {
     "rawSql": "(SELECT pr.value as AlkalinityDosing, pr.time FROM tank_data_schema.parameter_reading as pr\r\nFULL OUTER JOIN tank_data_schema.parameter as p ON p.id = pr.parameter_id\r\nWHERE p.name = 'alkalinity-dosing'AND pr.tank_id = 1 AND pr.show_in_dashboard = TRUE\r\nORDER BY pr.time)\r\nUNION\r\n((SELECT pr.value as AlkalinityDosing, now() FROM tank_data_schema.parameter_reading as pr\r\nFULL OUTER JOIN tank_data_schema.parameter as p ON p.id = pr.parameter_id\r\nWHERE p.name = 'alkalinity-dosing' AND pr.tank_id = 1 AND pr.show_in_dashboard = TRUE\r\nORDER BY pr.time DESC) LIMIT 1)\r\nORDER BY time;"
    }
   ]
  },
  {
   "title": "Nitrate",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 6, "x": 18, "y": 0 },
   "targets": [
    {
     "rawSql": "SELECT pr.value as Nitrate, pr.time FROM tank_data_schema.parameter_reading as pr\r\nFULL OUTER JOIN tank_data_schema.parameter as p ON p.id = pr.parameter_id\r\nWHERE p.name = 'nitrate' AND pr.show_in_dashboard = TRUE\r\nORDER BY pr.time;"
    }
   ]
  },
  {
   "title": "Calcium",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 6, "x": 6, "y": 10 },
   "targets": [
    {
     "rawSql": "SELECT pr.value as calcium, pr.time, a.low_limit as low_limit, a.high_limit as high_limit FROM tank_data_schema.parameter_reading as pr\r\nFULL OUTER JOIN tank_data_schema.parameter as p ON p.id = pr.parameter_id\r\nFULL OUTER JOIN tank_data_schema.alarm as a on a.parameter_id = pr.parameter_id\r\nWHERE p.name = 'calcium' AND pr.show_in_dashboard = TRUE\r\nORDER BY pr.time;"
    }
   ]
  },
  {
   "title": "Calcium Dosing",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 6, "x": 12, "y": 10 },
   "targets": [
    {
     "rawSql": "(SELECT pr.value as CalciumDosing, pr.time FROM tank_data_schema.parameter_reading as pr\r\nFULL OUTER JOIN tank_data_schema.parameter as p ON p.id = pr.parameter_id\r\nWHERE p.name = 'calcium-dosing' AND pr.tank_id = 1 AND pr.show_in_dashboard = TRUE\r\nORDER BY pr.time)\r\nUNION\r\n((SELECT pr.value as CalciumDosing, now() FROM tank_data_schema.parameter_reading as pr\r\nFULL OUTER JOIN tank_data_schema.parameter as p ON p.id = pr.parameter_id\r\nWHERE p.name = 'calcium-dosing' AND pr.tank_id = 1 AND pr.show_in_dashboard = TRUE\r\nORDER BY pr.time DESC) LIMIT 1)\r\nORDER BY time;"
    }
   ]
  },
  {
   "title": "Phosphate",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 6, "x": 18, "y": 10 },
   "targets": [
    {
     "rawSql": "SELECT pr.value as Phosphate, pr.time FROM tank_data_schema.parameter_reading as pr\r\nFULL OUTER JOIN tank_data_schema.parameter as p ON p.id = pr.parameter_id\r\nWHERE p.name = 'phosphate' AND pr.show_in_dashboard = TRUE\r\nORDER BY pr.time;"
    }
   ]
  },
  {
   "title": "Temperature",
   "type": "timeseries",
   "gridPos": { "h": 15, "w": 6, "x": 0, "y": 15 },
   "targets": [
    {
     "rawSql": "SELECT pr.value as temperature, pr.time, a.low_limit as low_limit, a.high_limit as high_limit FROM tank_data_schema.parameter_reading as pr\r\nFULL OUTER JOIN tank_data_schema.parameter as p ON p.id = pr.parameter_id\r\nFULL OUTER JOIN tank_data_schema.alarm as a on a.parameter_id = pr.parameter_id\r\nWHERE p.name = 'temperature' AND pr.show_in_dashboard = TRUE\r\nORDER BY pr.time;"
    }
   ]
  },
  {
   "title": "Magnesium",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 6, "x": 6, "y": 20 },
   "targets": [
    {
     "rawSql": "SELECT pr.value as magnesium, pr.time, a.low_limit as low_limit, a.high_limit as high_limit FROM tank_data_schema.parameter_reading as pr\r\nFULL OUTER JOIN tank_data_schema.parameter as p ON p.id = pr.parameter_id\r\nFULL OUTER JOIN tank_data_schema.alarm as a on a.parameter_id = pr.parameter_id\r\nWHERE p.name = 'magnesium' AND pr.show_in_dashboard = TRUE\r\nORDER BY pr.time;"
    }
   ]
  },
  {
   "title": "Magnesium Dosing",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 6, "x": 12, "y": 20 },
   "targets": [
    {
     "rawSql": "(SELECT pr.value as MagnesiumDosing, pr.time FROM tank_data_schema.parameter_reading as pr\r\nFULL OUTER JOIN tank_data_schema.parameter as p ON p.id = pr.parameter_id\r\nWHERE p.name = 'magnesium-dosing' AND pr.tank_id = 1 AND pr.show_in_dashboard = TRUE\r\nORDER BY pr.time)\r\nUNION\r\n((SELECT pr.value as MagnesiumDosing, now() FROM tank_data_schema.parameter_reading as pr\r\nFULL OUTER JOIN tank_data_schema.parameter as p ON p.id = pr.parameter_id\r\nWHERE p.name = 'magnesium-dosing' AND pr.tank_id = 1 AND pr.show_in_dashboard = TRUE\r\nORDER BY pr.time DESC) LIMIT 1)\r\nORDER BY time;"
    }
   ]
  },
  {
   "title": "Potassium",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 6, "x": 18, "y": 20 },
   "targets": [
    {
     "rawSql": "SELECT pr.value as Potassium, pr.time FROM tank_data_schema.parameter_reading as pr\r\nFULL OUTER JOIN tank_data_schema.parameter as p ON p.id = pr.parameter_id\r\nWHERE p.name = 'potassium' AND pr.show_in_dashboard = TRUE\r\nORDER BY pr.time;"
    }
   ]
  }
 ]
}